root = "."
tmp_dir = "tmp"

[build]
  cmd = "sqlc generate && go build -o ./tmp/main ."
  bin = "./tmp/main"
  delay = 1000
  exclude_dir = ["assets", "tmp", "vendor"]
  include_ext = ["go", "tpl", "tmpl", "sql"]
  exclude_regex = ["_test\\.go"]

[screen]
  clear_on_rebuild = true